### ISSUE TITLE
update JUCE 6.1.2 

### ISSUE THREAD

**Issue by KottV** [Chowdhury-DSP/chowdsp_utils#60]
Hi!

I'm preparing to update my lv2 fork from 6.0.8 to 6.1.2 and found some errors (type mismatch) during compile with 6.1.2
```
/home/kv/src/audio/ChowKick/modules/chowdsp_utils/DSP/SIMD/chowdsp_SIMDUtils.h:197:70: error: type/value mismatch at argument 2 in template parameter list for ‘template<class T, class A> class xsimd::batch’
  197 |     using x_type = xsimd::batch<T, juce::dsp::SIMDRegister<T>::size()>;
```
etc

also there is a 6.1.2 branch for testing https://github.com/lv2-porting-project/JUCE/tree/6.1.2-lv2

**Comment by KottV** [comment]
my stupid, somehow forget to `git submodule update --init --recursive`
